### ISSUE TITLE
Page scrolling issue when the header area is bigger than the area to be scrolled

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#1528]
When the height of the area to be scrolled is less than the header,
after the header is minimized the scroll resets, and you get a situation where you cant scroll down

Example:
![2018-03-10 14 20 46](https://user-images.githubusercontent.com/19532384/37242278-4cb50b3e-246f-11e8-8587-c6eda4d1e2a3.gif)

Expected behavior (normal behavior when theres enough scroll):
![2018-03-10 14 18 43](https://user-images.githubusercontent.com/19532384/37242269-2c1a43b2-246f-11e8-8d2e-aaa44ca7249e.gif)

How to reproduce: 
Just make sure you have some vertical scroll which is bigger than the minimize threshold (i think its 20px) but less than your page's header height (the easiest way is to open dev tools and play with its height)

**Comment by amiryonatan** [comment]
Fixed: #1535

**Comment by D0vydas** [comment]
@amiryonatan This still reproduces https://www.youtube.com/watch?v=i5QfcgSPHuc

**Comment by amiryonatan** [comment]
@D0vydas hey are u sure u are using the latest version ? 
How can I reproduce it ?

**Comment by D0vydas** [comment]
@amiryonatan 
Yes, we're using the latest one.
Actually I don't know exact scenario. This happens when scrolling area is very short.

**Comment by amiryonatan** [comment]
@D0vydas is there a project i can see the bug happening live ?
otherwise, in my env i can't reproduce it .. I need to understand the edge case that I missed ..

**Comment by D0vydas** [comment]
@amiryonatan This happens in Wix Events -> Emails -> Reminder (you can see in YouTube link). It does not reproduce on Mac screen, we noticed this on 1920x1200 monitor.

**Comment by amiryonatan** [comment]
Fixed
